import { describe, it, expect } from 'vitest';
import {
  generateScoreHash,
  parseScoreComment,
  verifyScoreComment,
} from './scoreVerification';

describe('scoreVerification core module', () => {
  it('generates consistent verification hash for given inputs', () => {
    const hash1 = generateScoreHash({
      puzzleId: 'daily-2026-09-12',
      username: 'testuser',
      pushes: 8,
      moves: 45,
      solveTime: 65,
      stars: 3,
      blockOrderEmojis: '🔴 🔵 🟢',
    });

    const hash2 = generateScoreHash({
      puzzleId: 'daily-2026-09-12',
      username: 'testuser',
      pushes: 8,
      moves: 45,
      solveTime: 65,
      stars: 3,
      blockOrderEmojis: '🔴 🔵 🟢',
    });

    expect(hash1).toMatch(/^BD-[A-F0-9]{4}-[A-F0-9]{4}$/);
    expect(hash1).toBe(hash2);
  });

  it('correctly parses score comment generated by postScoreComment formatting', () => {
    const formattedComment = `### **Block Down Solution**

**Daily Puzzle #1**
- ⭐ **Rating**: ⭐⭐⭐ (Par Master)
- 🚀 **Pushes**: **8** / 8 Par
- 👣 **Moves**: 45 steps
- ⏱️ **Solve Time**: 1m 05s
- 🧩 **Block Order**: >! 🔴 🔵 🟢 !<
- 🔥 **Streak**: 3 Days

\`HASH • BD-1234-5678\``;

    const parsed = parseScoreComment(formattedComment);
    expect(parsed.claimedCode).toBe('BD-1234-5678');
    expect(parsed.pushes).toBe(8);
    expect(parsed.moves).toBe(45);
    expect(parsed.solveTime).toBe(65); // 1m 05s -> 65 seconds
    expect(parsed.stars).toBe(3);
    expect(parsed.blockOrderEmojis).toBe('🔴 🔵 🟢');
  });

  it('correctly verifies a real score comment generated for a user', () => {
    const puzzleId = 'daily-2026-09-12';
    const username = 'player_one';
    const pushes = 10;
    const moves = 52;
    const solveTime = 45;
    const stars = 2;
    const blockOrder = '🟦 🟨';

    const hash = generateScoreHash({
      puzzleId,
      username,
      pushes,
      moves,
      solveTime,
      stars,
      blockOrderEmojis: blockOrder,
    });

    const commentBody = `### **Block Down Solution**

**Daily Puzzle #5**
- ⭐ **Rating**: ⭐⭐ (Great Job)
- 🚀 **Pushes**: **${pushes}** / 8 Par
- 👣 **Moves**: ${moves} steps
- ⏱️ **Solve Time**: 45s
- 🧩 **Block Order**: >! ${blockOrder} !<

\`HASH • ${hash}\``;

    const verification = verifyScoreComment({
      text: commentBody,
      commentAuthor: 'u/player_one',
      mappedPuzzleId: puzzleId,
    });

    expect(verification.isLegit).toBe(true);
    expect(verification.claimedCode).toBe(hash);
    expect(verification.matchedUsername).toBe('player_one');
    expect(verification.matchedPuzzleId).toBe(puzzleId);
  });

  it('rejects tampered score comments', () => {
    const puzzleId = 'daily-2026-09-12';
    const username = 'honest_player';

    const validHash = generateScoreHash({
      puzzleId,
      username,
      pushes: 15,
      moves: 80,
      solveTime: 120,
      stars: 1,
    });

    const tamperedComment = `### **Block Down Solution**

**Daily Puzzle #5**
- ⭐ **Rating**: ⭐⭐⭐ (Par Master)
- 🚀 **Pushes**: **5** / 10 Par
- 👣 **Moves**: 80 steps
- ⏱️ **Solve Time**: 2m 00s

\`HASH • ${validHash}\``;

    const verification = verifyScoreComment({
      text: tamperedComment,
      commentAuthor: username,
      mappedPuzzleId: puzzleId,
    });

    expect(verification.isLegit).toBe(false);
  });
});
